/*
 *	This file is part of OGS Engine
 *	Copyright (C) 1996-1997 Id Software, Inc.
 *	Copyright (C) 2018 BlackPhrase
 *
 *	OGS Engine is free software: you can redistribute it and/or modify
 *	it under the terms of the GNU General Public License as published by
 *	the Free Software Foundation, either version 3 of the License, or
 *	(at your option) any later version.
 *
 *	OGS Engine is distributed in the hope that it will be useful,
 *	but WITHOUT ANY WARRANTY; without even the implied warranty of
 *	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *	GNU General Public License for more details.
 *
 *	You should have received a copy of the GNU General Public License
 *	along with OGS Engine. If not, see <http://www.gnu.org/licenses/>.
 */

/// @file

#include "quakedef.h"

/*
===============================================================================

						BUILT-IN FUNCTIONS

===============================================================================
*/

/*
{
pfnPrecacheModel = 0xb3cece40 <PF_precache_model_I>,
pfnPrecacheSound = 0xb3cec330 <PF_precache_sound_I>,
pfnSetModel = 0xb3cea250 <PF_setmodel_I>,
pfnModelIndex = 0xb3cea330 <PF_modelindex>,
pfnModelFrames = 0xb3cea340 <ModelFrames>,
pfnSetSize = 0xb3cea220 <PF_setsize_I>,
pfnChangeLevel = 0xb3ceeb60 <PF_changelevel_I>,
pfnGetSpawnParms = 0xb3ceeb20 <PF_setspawnparms_I>,
pfnSaveSpawnParms = 0xb3cf0a70 <SaveSpawnParms>,
pfnVecToYaw = 0xb3cea570 <PF_vectoyaw_I>,
pfnVecToAngles = 0xb3cea610 <PF_vectoangles_I>,
pfnMoveToOrigin = 0xb3d1a330 <SV_MoveToOrigin_I>,
pfnChangeYaw = 0xb3ceda20 <PF_changeyaw_I>,
pfnChangePitch = 0xb3cedb00 <PF_changepitch_I>,
pfnFindEntityByString = 0xb3cec1a0 <FindEntityByString>,
pfnGetEntityIllum = 0xb3cec280 <GetEntityIllum>,
pfnFindEntityInSphere = 0xb3cebd10 <FindEntityInSphere>,
pfnFindClientInPVS = 0xb3ceb730 <PF_checkclient_I>,
pfnEntitiesInPVS = 0xb3ceb9e0 <PVSFindEntities>,
pfnMakeVectors = 0xb3cea060 <PF_makevectors_I>,
pfnAngleVectors = 0xb3ce2570 <AngleVectors>,
pfnCreateEntity = 0xb3cebed0 <PF_Spawn_I>,
pfnRemoveEntity = 0xb3cebf70 <PF_Remove_I>,
pfnCreateNamedEntity = 0xb3cebee0 <CreateNamedEntity>,
pfnMakeStatic = 0xb3cee860 <PF_makestatic_I>,
pfnEntIsOnFloor = 0xb3ced5e0 <PF_checkbottom_I>,
pfnDropToFloor = 0xb3ced3c0 <PF_droptofloor_I>,
pfnWalkMove = 0xb3ced2e0 <PF_walkmove_I>,
pfnSetOrigin = 0xb3cea0b0 <PF_setorigin_I>,
pfnEmitSound = 0xb3cea800 <PF_sound_I>,
pfnEmitAmbientSound = 0xb3cea640 <PF_ambientsound_I>,
pfnTraceLine = 0xb3ceb330 <PF_traceline_DLL>,
pfnTraceToss = 0xb3ceb450 <PF_TraceToss_DLL>,
pfnTraceMonsterHull = 0xb3ceb530 <TraceMonsterHull>,
pfnTraceHull = 0xb3cea920 <TraceHull>,
pfnTraceModel = 0xb3ceaa20 <TraceModel>,
pfnTraceTexture = 0xb3ceae60 <TraceTexture>,
pfnTraceSphere = 0xb3ceaa10 <TraceSphere>,
pfnGetAimVector = 0xb3ced600 <PF_aim_I>,
pfnServerCommand = 0xb3cebcb0 <PF_localcmd_I>,
pfnServerExecute = 0xb3cebd00 <PF_localexec_I>,
pfnClientCommand = 0xb3cebbc0 <PF_stuffcmd_I>,
pfnParticleEffect = 0xb3cea620 <PF_particle_I>,
pfnLightStyle = 0xb3ced520 <PF_lightstyle_I>,
pfnDecalIndex = 0xb3ced4c0 <PF_DecalIndex>,
pfnPointContents = 0xb3ced5f0 <PF_pointcontents_I>,
pfnMessageBegin = 0xb3cee250 <PF_MessageBegin_I>,
pfnMessageEnd = 0xb3cee390 <PF_MessageEnd_I>,
pfnWriteByte = 0xb3cee6b0 <PF_WriteByte_I>,
pfnWriteChar = 0xb3cee6e0 <PF_WriteChar_I>,
pfnWriteShort = 0xb3cee710 <PF_WriteShort_I>,
pfnWriteLong = 0xb3cee740 <PF_WriteLong_I>,
pfnWriteAngle = 0xb3cee770 <PF_WriteAngle_I>,
pfnWriteCoord = 0xb3cee7a0 <PF_WriteCoord_I>,
pfnWriteString = 0xb3cee7f0 <PF_WriteString_I>,
pfnWriteEntity = 0xb3cee830 <PF_WriteEntity_I>,
pfnCVarRegister = 0x981fd7a4 <meta_CVarRegister(cvar_s*)>,
pfnCVarGetFloat = 0xb3cf0980 <CVarGetFloat>,
pfnCVarGetString = 0xb3cf0990 <CVarGetString>,
pfnCVarSetFloat = 0xb3cf09b0 <CVarSetFloat>,
pfnCVarSetString = 0xb3cf09c0 <CVarSetString>,
pfnAlertMessage = 0xb3cfe510 <AlertMessage>,
pfnEngineFprintf = 0xb3cfe6a0 <EngineFprintf>,
pfnPvAllocEntPrivateData = 0xb3cf0730 <PvAllocEntPrivateData>,
pfnPvEntPrivateData = 0xb3cf0790 <PvEntPrivateData>,
pfnFreeEntPrivateData = 0xb3cf07b0 <FreeEntPrivateData>,
pfnSzFromIndex = 0xb3cf0910 <SzFromIndex>,
pfnAllocString = 0xb3cf09f0 <AllocEngineString>,
pfnGetVarsOfEnt = 0xb3cf0920 <GetVarsOfEnt>,
pfnPEntityOfEntOffset = 0xb3cf0860 <PEntityOfEntOffset>,
pfnEntOffsetOfPEntity = 0xb3cf0870 <EntOffsetOfPEntity>,
pfnIndexOfEdict = 0xb3cf0880 <IndexOfEdict>,
pfnPEntityOfEntIndex = 0xb3cf08c0 <PEntityOfEntIndex>,
pfnFindEntityByVars = 0xb3cf0930 <FindEntityByVars>,
pfnGetModelPtr = 0xb3cf0ad0 <GetModelPtr>,
pfnRegUserMsg = 0x981fd94a <meta_RegUserMsg(char const*, int)>,
pfnAnimationAutomove = 0xb3cf53e0 <AnimationAutomove>,
pfnGetBonePosition = 0xb3cf53f0 <GetBonePosition>,
pfnFunctionFromName = 0xb3cff2f0 <FunctionFromName>,
pfnNameForFunction = 0xb3cfe6c0 <NameForFunction>,
pfnClientPrintf = 0xb3cea470 <ClientPrintf>,
pfnServerPrint = 0xb3cea450 <ServerPrint>,
pfnCmd_Args = 0xb3cbf7c0 <Cmd_Args>,
pfnCmd_Argv = 0xb3cbf790 <Cmd_Argv>,
pfnCmd_Argc = 0xb3cbf770 <Cmd_Argc>,
pfnGetAttachment = 0xb3cf54c0 <GetAttachment>,
pfnCRC32_Init = 0xb3cc8bd0 <CRC32_Init>,
pfnCRC32_ProcessBuffer = 0xb3cc8c10 <CRC32_ProcessBuffer>,
pfnCRC32_ProcessByte = 0xb3cc8bf0 <CRC32_ProcessByte>,
pfnCRC32_Final = 0xb3cc8be0 <CRC32_Final>,
pfnRandomLong = 0xb3ceedd0 <RandomLong>,
pfnRandomFloat = 0xb3ceed70 <RandomFloat>,
pfnSetView = 0xb3cedbe0 <PF_setview_I>,
pfnTime = 0xb3cea090 <PF_Time>,
pfnCrosshairAngle = 0xb3cedc80 <PF_crosshairangle_I>,
pfnLoadFileForMe = 0xb3cc6ab0 <COM_LoadFileForMe>,
pfnFreeFile = 0xb3cc62b0 <COM_FreeFile>,
pfnEndSection = 0xb3ce0750 <Host_EndSection>,
pfnCompareFileTime = 0xb3cc6ae0 <COM_CompareFileTime>,
pfnGetGameDir = 0xb3cc6b80 <COM_GetGameDir>,
pfnCvar_RegisterVariable = 0x981fd7a4 <meta_CVarRegister(cvar_s*)>,
pfnFadeClientVolume = 0xb3ceee30 <PF_FadeVolume>,
pfnSetClientMaxspeed = 0xb3ceef50 <PF_SetClientMaxspeed>,
pfnCreateFakeClient = 0xb3ceddc0 <PF_CreateFakeClient_I>,
pfnRunPlayerMove = 0xb3cedfd0 <PF_RunPlayerMove_I>,
pfnNumberOfEntities = 0xb3ced0c0 <PF_NumberOfEntities_I>,
pfnGetInfoKeyBuffer = 0xb3ced100 <PF_GetInfoKeyBuffer_I>,
pfnInfoKeyValue = 0xb3ced160 <PF_InfoKeyValue_I>,
pfnSetKeyValue = 0xb3ced170 <PF_SetKeyValue_I>,
pfnSetClientKeyValue = 0xb3ced220 <PF_SetClientKeyValue_I>,
pfnIsMapValid = 0xb3ced070 <PF_IsMapValid_I>,
pfnStaticDecal = 0xb3ceea30 <PF_StaticDecal>,
pfnPrecacheGeneric = 0xb3cecf70 <PF_precache_generic_I>,
pfnGetPlayerUserId = 0xb3ceefb0 <PF_GetPlayerUserId>,
pfnBuildSoundMsg = 0xb3cef140 <PF_BuildSoundMsg_I>,
pfnIsDedicatedServer = 0xb3cef220 <PF_IsDedicatedServer>,
pfnCVarGetPointer = 0xb3cf09a0 <CVarGetPointer>,
pfnGetPlayerWONId = 0xb3cef010 <PF_GetPlayerWONId>,
pfnInfo_RemoveKey = 0xb3ced210 <PF_RemoveKey_I>,
pfnGetPhysicsKeyValue = 0xb3cef280 <PF_GetPhysicsKeyValue>,
pfnSetPhysicsKeyValue = 0xb3cef2f0 <PF_SetPhysicsKeyValue>,
pfnGetPhysicsInfoString = 0xb3cef230 <PF_GetPhysicsInfoString>,
pfnPrecacheEvent = 0xb3cec450 <EV_Precache>,
pfnPlaybackEvent = 0xb3cec810 <EV_Playback>,
pfnSetFatPVS = 0xb3d0cdd0 <SV_FatPVS>,
pfnSetFatPAS = 0xb3d0cf70 <SV_FatPAS>,
pfnCheckVisibility = 0xb3d0dde0 <SV_CheckVisibility>,
pfnDeltaSetField = 0xb3ccc610 <DELTA_SetField>,
pfnDeltaUnsetField = 0xb3ccc690 <DELTA_UnsetField>,
pfnDeltaAddEncoder = 0xb3ccdd50 <DELTA_AddEncoder>,
pfnGetCurrentPlayer = 0xb3cef380 <PF_GetCurrentPlayer>,
pfnCanSkipPlayer = 0xb3cef3c0 <PF_CanSkipPlayer>,
pfnDeltaFindField = 0xb3ccc5a0 <DELTA_FindFieldIndex>,
pfnDeltaSetFieldByIndex = 0xb3ccc710 <DELTA_SetFieldByIndex>,
pfnDeltaUnsetFieldByIndex = 0xb3ccc730 <DELTA_UnsetFieldByIndex>,
pfnSetGroupMask = 0xb3cef420 <PF_SetGroupMask>,
pfnCreateInstancedBaseline = 0xb3cef440 <PF_CreateInstancedBaseline>,
pfnCvar_DirectSet = 0xb3cef4c0 <PF_Cvar_DirectSet>,
pfnForceUnmodified = 0xb3cef4d0 <PF_ForceUnmodified>,
pfnGetPlayerStats = 0xb3cef640 <PF_GetPlayerStats>,
pfnAddServerCommand = 0x981fd63f <meta_AddServerCommand(char*, void (*)())>,
pfnVoice_GetClientListening = 0xb3cfe3f0 <Voice_GetClientListening>,
pfnVoice_SetClientListening = 0xb3cfe470 <Voice_SetClientListening>,
pfnGetPlayerAuthId = 0,
pfnSequenceGet = 0,
pfnSequencePickSentence = 0,
pfnGetFileSize = 0,
pfnGetApproxWavePlayLen = 0,
pfnIsCareerMatch = 0,
pfnGetLocalizedStringLength = 0,
pfnRegisterTutorMessageShown = 0,
pfnGetTimesTutorMessageShown = 0,
ProcessTutorMessageDecayBuffer = 0,
ConstructTutorMessageDecayBuffer = 0,
ResetTutorMessageDecayData = 0,
pfnQueryClientCvarValue = 0,
pfnQueryClientCvarValue2 = 0,
pfnCheckParm = 0
}
*/